### ISSUE TITLE
get error when installing

### ISSUE THREAD

**Issue by brody182** [cdukes/bones-for-genesis-2-0#25]
get a warning when ruining grunt

C:\xampp\htdocs\wordpress\wp-content\themes\bones-for-genesis>grunt
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "sass:build" (sass) task
Error: File to import not found or unreadable: ../bower_components/Colors/sass/v
ariables.
       Load paths:
         C:/xampp/htdocs/wordpress/wp-content/themes/bones-for-genesis/sass
         C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-core-1.1.0.alpha.3/styleshe
ets
         Compass::SpriteImporter
        on line 5 of sass/style.scss
  Use --trace for backtrace.
Warning: Exited with error code 65 Use --force to continue.

Aborted due to warnings.

**Comment by EmilEriksen** [comment]
I got the same error yesterday. Remove node_modules and run `sudo npm cache clean`.

**Comment by brody182** [comment]
is node_modules supposed to be in my theme directory? that is a big file

**Comment by EmilEriksen** [comment]
Yes. This directory contains all the modules needed to build the theme. These modules compile the sass, minify the javascript and css and so on. The directory is not needed to active the theme - just build it.
