### ISSUE TITLE
Img class attr is getting &nbsp added

### ISSUE THREAD

**Issue by ellecarrier** [cdukes/bones-for-genesis-2-0#26]
I noticed that images inserted via the content editor are getting `&nbsp;` added to the class attr, which is breaking layouts for things like: **.alignright** as what is being output is `class="&nbsp;alignright "`

The source of the issue is in **post.php** around line 191 `add_filter( 'the_content', 'bfg_hard_space_expressions' );`

**Comment by cdukes** [comment]
Are you using the latest version? `bfg_hard_space_expressions` was removed in a5470f5806cdc9ad39a7a9ca4fb0721eb041d675

**Comment by ellecarrier** [comment]
Hi @cdukes ...Aha yes I see now, thanks for the headsup! I was using a version from a few weeks back.
