### ISSUE TITLE
File to import not found - Running Grunt for the first time following your instructions.

### ISSUE THREAD

**Issue by dpav02** [cdukes/bones-for-genesis-2-0#27]
Running "sass:build" (sass) task
Error: File to import not found or unreadable: ../bower_components/Colors/sass/variables.

**Comment by cdukes** [comment]
Did you run `bower install` first?

**Comment by cdukes** [comment]
Just committed 862a01e0095a1a7fe10ce0e3c3c1b974753088ed. Can you confirm the fix?

**Comment by dpav02** [comment]
Yes, that worked! Thank you!

I'm very new to front-end development, but I can't wait to jump in. Thank you for this starter theme! I have much to learn! 

I'm already thinking about swapping out compass for bourbon/neat and instead of using the autoprefixer and the csso by itself, I think I might just use postcss and then add in whatever postcss plugins I need (such as autoprefixer, pixrem etc)

**Comment by cdukes** [comment]
Welcome to frontend =)
