### ISSUE TITLE
No bower_components folder on install

### ISSUE THREAD

**Issue by leethegreengiant** [cdukes/bones-for-genesis-2-0#28]
Hi,

On install of the latest version that I'd like to use on a new project it seems that the bower_components does not install or is not downloaded on initial clone.

I would really appreciate your help.

I am working on a macbook pro running El Capitan 10.11.3

Many thanks,
Lee

**Comment by cdukes** [comment]
@leethegreengiant 

Are you running `bower install` on the cloned/downloaded repo?

**Comment by leethegreengiant** [comment]
Sorry @cdukes I hadn't run the bower install on the directory DOH!

It's now working fine.

Thanks so much for your help :)
