### ISSUE TITLE
Removal of Bower, npm update

### ISSUE THREAD

**Issue by chillybin** [cdukes/bones-for-genesis-2-0#34]
Hey Cooper, 

Since Bower has been removed, we just use `npm update --save-dev` right?

No need to run `npm install` to get any dependencies cleared up?

```
You'll need Node.js, Grunt, and Bower.

git clone https://github.com/cdukes/bones-for-genesis-2-0.git genesis-bfg
cd genesis-bfg
npm update --save-dev && bower update --save
grunt
```

**Comment by cdukes** [comment]
`npm update --save-dev` for the grunt deps, and `npm update --save` for the frontend deps
