### ISSUE TITLE
Webpack error after updating to 20170704

### ISSUE THREAD

**Issue by Fortyfive** [cdukes/bones-for-genesis-2-0#35]
Hi Cooper, I seem to have ran into an error using Webpack after the update:

ERROR in ./js/scripts.js
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/babel-core'
	Error: ENOENT: no such file or directory, open '/Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/babel-core'
	
	Error loading /Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/babel-core as "babel-core" from /Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/node_modules/babel-loader/lib/index.js

ERROR in ./js/admin.js
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/babel-core'
	Error: ENOENT: no such file or directory, open '/Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/babel-core'
	
	Error loading /Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/babel-core as "babel-core" from /Users/dh/Documents/Websites/www.mpp.dev/wp-content/themes/develop/node_modules/babel-loader/lib/index.js

Thanks

**Comment by cdukes** [comment]
I'm not able to reproduce with a fresh node_modules install. This is likely an issue with your system.
