### ISSUE TITLE
PHP-CS-Fixer Error

### ISSUE THREAD

**Issue by Fortyfive** [cdukes/bones-for-genesis-2-0#37]
Hi Cooper, I've cloned a new copy of BFG and upon running build I get this error:

sh: php-cs-fixer: command not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `run-p build:* -s`
npm ERR! Exit status 1

Thanks

**Comment by cdukes** [comment]
You need to install https://github.com/FriendsOfPHP/PHP-CS-Fixer
