### ISSUE TITLE
Function create_function() is deprecated as of PHP 7.2.0

### ISSUE THREAD

**Issue by luke-au** [cdukes/bones-for-genesis-2-0#39]
create_function() DEPRECATED as of PHP 7.2.0. Relying on this function is highly discouraged.
http://php.net/manual/en/function.create-function.php

https://github.com/cdukes/bones-for-genesis-2-0/blob/dcbaf195f7eb36134e116d3e6ef0d81a94dbb805/includes/admin/admin-functions.php#L52

Maybe use: 
`add_filter('jpeg_quality', function($arg){return 80;});`

**Comment by cdukes** [comment]
Fixed now
